# Dockerfile (backend)
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# Cài nodemon toàn cục
RUN npm install -g nodemon

# Cài deps trong dự án
RUN npm install

COPY . .

EXPOSE 5000

CMD ["nodemon", "app.js"]
